language: rust
rust:
- stable
env:
- RUST_BACKTRACE=full CARGO_INCREMENTAL=0
matrix:
  include:
  # test 32-bit
  - name: "i686-unknown-linux-musl"
    env: TARGET=i686-unknown-linux-musl RUST_BACKTRACE=full CARGO_INCREMENTAL=0
    addons:
      apt:
        packages:
        - gcc-multilib
        - musl-tools
  # test nightly channel
  - os: linux
    rust: nightly
os:
- linux
- osx
- windows
script:
- cargo test --all
